README.md

Feature/no ref/edit readme (#48)

---

app/src/main/java/com/sugiartha/juniorandroid/HitungBMIActivity.java
app/src/main/res/layout/activity_hitung_bmi.xml

perubahan tampilan pada berat badan dan tinggi badan

redesign bmi

---

app/src/main/java/com/sugiartha/juniorandroid/LingkaranActivity.java
app/src/main/res/layout/activity_lingkaran.xml

feat: redesign lingkaran activity

---

app/src/main/AndroidManifest.xml
app/src/main/res/layout/activity_list_view.xml

edit font pada activity_list_view.xml dan attribute ListViewActivity pada android manifest
resolve #80

feat: redesign activity_list_view.xml

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/sugiartha/juniorandroid/GPS.java
app/src/main/res/drawable/btn_outlined_selector.xml
app/src/main/res/drawable/ic_back_arrow.xml
app/src/main/res/layout/activity_gps.xml

- redesign gps activity
- fix bug ketika get location
- mengubah warna state button outlined
- menambahkan background location pada android manifest
- menambahkan icon arrow untuk navigasi back pressed

feat: redesign gps activity

---

app/src/main/java/com/sugiartha/juniorandroid/NamaActivity.java
app/src/main/res/drawable/form_edit.xml
app/src/main/res/layout/activity_nama.xml
app/src/main/res/values/colors.xml

menambah validasi pada NamaActivity, mengurangi radius pada form_edit, menambah warna error di colors.xml

feat: menambah validasi pada NamaActivity

---

app/src/main/java/com/sugiartha/juniorandroid/AddEditActivity.java
app/src/main/java/com/sugiartha/juniorandroid/NamaActivity.java
app/src/main/java/com/sugiartha/juniorandroid/SharedPreferenceActivity.java
app/src/main/res/drawable/form_edit_error.xml
app/src/main/res/drawable/form_edit_success.xml
app/src/main/res/layout/activity_add_edit.xml
app/src/main/res/layout/activity_shared_preference.xml
app/src/main/res/values/colors.xml

menambah form input (error & success), menambah warna baru (success/green) di colors.xml, dan edit semua form yang telah dengan design validasi yang sudah dibuat
resolve #101

feat: menambah form input resource (error & success)

---

.idea/jarRepositories.xml
app/build.gradle
app/src/main/java/com/sugiartha/juniorandroid/GPS.java
app/src/main/res/drawable/btn_outlined_selector.xml
app/src/main/res/layout/activity_gps.xml
build.gradle

feat: add alerter dependency, change style for disabled btn_outlined and add alert when getting location in gps activity

feat: add alerter dependency

---

app/src/main/java/com/sugiartha/juniorandroid/GPS.java
app/src/main/res/layout/activity_gps.xml

bugfix:
- __gps activity__: lokasi tidak tampil pada saat button diclick di initial load/restart android studio  #108

bugfix: GPSActivity (GPS.java)

---

app/build.gradle

- Upgrade 'com.google.android.material:material:1.0.0' -> 'com.google.android.material:material:1.9.0'

Upgrade Material Component Version

---

app/src/main/java/com/sugiartha/juniorandroid/MainActivity.java
app/src/main/java/com/sugiartha/juniorandroid/adapter/CarouselAdapter.java
app/src/main/res/layout/carousel_layout.xml
app/src/main/res/layout/content_main.xml

- add new carousel adapter (CarouselAdapter.java)
- add carousel layout (carousel_layout.xml)
- add adapter in MainActivity and remove unnecessary code
- change the com.synnapps.carouselview.CarouselView with RecyclerView
- fix vertical spacing in MainActivity between Card and parent layout by adding margin bottom in Card Component

feat: redesign carousel

---

app/src/main/res/layout-land/content_main.xml

- Add landscape layout for content_main.xml (`res/layout-land/content_main.xml`)
> Note: no functional changes were made

feat: add landscape layout for content_main.xml

---

app/src/main/java/com/sugiartha/juniorandroid/NamaActivity.java
app/src/main/java/com/sugiartha/juniorandroid/components/DynamicAppBar.java
app/src/main/res/layout/activity_nama.xml
app/src/main/res/layout/dynamic_app_bar.xml

- Add app bar component so it can be used globally
- Add app bar component in NamaActivity

Redesign NamaActivity & Add AppBar Component

---

app/src/main/res/drawable/banner.xml
app/src/main/res/drawable/btn_gradient.xml
app/src/main/res/drawable/error_banner.xml
app/src/main/res/layout/activity_gps.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

- add tailwind colors
- add banner and error banner component in styles.xml
- modified couple of states for primary, secondary and add new gradient button
- change text color and font for button in activity_gps.xml
__Note: no functional changes were made__

Theme: add new colors and banner

---

app/build.gradle

- Update compileSdkVersion to 33
- Update targetSdkVersion to 33
- Update appcompat library to 1.6.1
- Update constraintlayout library to 2.1.4
- Update play-services-location library to 21.0.1
This update brings the project up to date with the latest Android SDK and libraries.

Update dependencies to latest versions

---

app/src/main/java/com/sugiartha/juniorandroid/NamaActivity.java
app/src/main/res/anim/slide_in.xml
app/src/main/res/drawable/vector_close.xml
app/src/main/res/drawable/vector_info.xml
app/src/main/res/layout/activity_nama.xml

- add slide in animation in res/anim
- add new vector icon (info & close)
- add banner in nama activity to show the result and add animation to it

Redesign NamaActivity

---

app/src/main/java/com/sugiartha/juniorandroid/SplashActivity.java
app/src/main/res/layout/activity_splash.xml
app/src/main/res/layout/content_main.xml

feat: change icon color on splash screen when animation ends and change main content background to pale blue
__no functional changes were made__

feat: change icon color on splash screen when animation ends

---

app/src/main/res/layout/activity_storage.xml

redesign storage

---

app/src/main/res/layout/activity_bilangan.xml

Fitur bilangan

---

app/build.gradle
app/src/main/java/com/sugiartha/juniorandroid/LoginActivity.java
app/src/main/java/com/sugiartha/juniorandroid/SignupActivity.java
app/src/main/java/com/sugiartha/juniorandroid/helper/AuthDao.java
app/src/main/java/com/sugiartha/juniorandroid/helper/DbHelper.java
app/src/main/java/com/sugiartha/juniorandroid/model/Auth.java
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_signup.xml
app/src/main/res/layout/spinner_item.xml
app/src/main/res/values/arrays.xml

- add bcrypt dependency
- add model auth model
- add auth helper
- add spinner item
- add arrays.xml for gender spinner

feat: add auth functionality with sqlite db

---

app/src/main/java/com/sugiartha/juniorandroid/MainActivity.java

- set the visibility of button logout to gone when user not logged in

fix: make logout button GONE when user not logged in

---

app/src/main/java/com/sugiartha/juniorandroid/KalkulatorActivity.java
app/src/main/res/layout/activity_kalkulator.xml

speedrun redesign kalkulator
